###############################################################
###############################################################
[2016-07-01 17:28:06]: Symfony\Component\Debug\Exception\ContextErrorException   codigo: 0
  mensaje: Notice: Memcache::connect(): Server localhost (tcp 11211, udp 0) failed with: Connection refused (111)
  clase: /var/www/SIGE4/vendor/boson/cache-bundle/UCI/Boson/CacheBundle/Cache/Cache.php
  linea: 54
  metodo: handleError
  traza: #0 [internal function]: Symfony\Component\Debug\ErrorHandler->handleError(8, 'Memcache::conne...', '/var/www/SIGE4/...', 54, Array)
#1 /var/www/SIGE4/vendor/boson/cache-bundle/UCI/Boson/CacheBundle/Cache/Cache.php(54): Memcache->connect('localhost', 11211)
#2 /var/www/SIGE4/app/cache/dev/appDevDebugProjectContainer.php(4223): UCI\Boson\CacheBundle\Cache\Cache->__construct(Array)
#3 /var/www/SIGE4/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Container.php(314): appDevDebugProjectContainer->getUci_Boson_CacheService()
#4 /var/www/SIGE4/app/cache/dev/appDevDebugProjectContainer.php(3423): Symfony\Component\DependencyInjection\Container->get('uci.boson.cache')
#5 /var/www/SIGE4/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Container.php(314): appDevDebugProjectContainer->getSige_Class_HandlerService()
#6 /var/www/SIGE4/src/SIGE/SecurityManagerBundle/Controller/AppController.php(55): Symfony\Component\DependencyInjection\Container->get('sige.class.hand...')
#7 [internal function]: SIGE\SecurityManagerBundle\Controller\AppController->getAppsAction(Object(Symfony\Component\HttpFoundation\Request), Object(FOS\RestBundle\Request\ParamFetcher))
#8 /var/www/SIGE4/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php(139): call_user_func_array(Array, Array)
#9 /var/www/SIGE4/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php(62): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1)
#10 /var/www/SIGE4/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/DependencyInjection/ContainerAwareHttpKernel.php(69): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#11 /var/www/SIGE4/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(185): Symfony\Component\HttpKernel\DependencyInjection\ContainerAwareHttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#12 /var/www/SIGE4/web/app_dev.php(30): Symfony\Component\HttpKernel\Kernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#13 {main}
 
###############################################################
###############################################################
[2016-07-01 17:29:32]: Symfony\Component\Debug\Exception\ContextErrorException   codigo: 0
  mensaje: Notice: Memcache::connect(): Server localhost (tcp 11211, udp 0) failed with: Connection refused (111)
  clase: /var/www/SIGE4/vendor/boson/cache-bundle/UCI/Boson/CacheBundle/Cache/Cache.php
  linea: 54
  metodo: handleError
  traza: #0 [internal function]: Symfony\Component\Debug\ErrorHandler->handleError(8, 'Memcache::conne...', '/var/www/SIGE4/...', 54, Array)
#1 /var/www/SIGE4/vendor/boson/cache-bundle/UCI/Boson/CacheBundle/Cache/Cache.php(54): Memcache->connect('localhost', 11211)
#2 /var/www/SIGE4/app/cache/dev/appDevDebugProjectContainer.php(4223): UCI\Boson\CacheBundle\Cache\Cache->__construct(Array)
#3 /var/www/SIGE4/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Container.php(314): appDevDebugProjectContainer->getUci_Boson_CacheService()
#4 /var/www/SIGE4/app/cache/dev/appDevDebugProjectContainer.php(3423): Symfony\Component\DependencyInjection\Container->get('uci.boson.cache')
#5 /var/www/SIGE4/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Container.php(314): appDevDebugProjectContainer->getSige_Class_HandlerService()
#6 /var/www/SIGE4/src/SIGE/SecurityManagerBundle/Controller/AppController.php(55): Symfony\Component\DependencyInjection\Container->get('sige.class.hand...')
#7 [internal function]: SIGE\SecurityManagerBundle\Controller\AppController->getAppsAction(Object(Symfony\Component\HttpFoundation\Request), Object(FOS\RestBundle\Request\ParamFetcher))
#8 /var/www/SIGE4/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php(139): call_user_func_array(Array, Array)
#9 /var/www/SIGE4/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php(62): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1)
#10 /var/www/SIGE4/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/DependencyInjection/ContainerAwareHttpKernel.php(69): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#11 /var/www/SIGE4/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(185): Symfony\Component\HttpKernel\DependencyInjection\ContainerAwareHttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#12 /var/www/SIGE4/web/app_dev.php(30): Symfony\Component\HttpKernel\Kernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#13 {main}
 
###############################################################
###############################################################
[2016-07-01 17:45:18]: Symfony\Component\Debug\Exception\ContextErrorException   codigo: 0
  mensaje: Notice: Undefined index: code
  clase: /var/www/SIGE4/src/SIGE/SecurityManagerBundle/Controller/UsuarioController.php
  linea: 140
  metodo: handleError
  traza: #0 /var/www/SIGE4/src/SIGE/SecurityManagerBundle/Controller/UsuarioController.php(140): Symfony\Component\Debug\ErrorHandler->handleError(8, 'Undefined index...', '/var/www/SIGE4/...', 140, Array)
#1 [internal function]: SIGE\SecurityManagerBundle\Controller\UsuarioController->postUsuarioAction(Object(Symfony\Component\HttpFoundation\Request))
#2 /var/www/SIGE4/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php(139): call_user_func_array(Array, Array)
#3 /var/www/SIGE4/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php(62): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1)
#4 /var/www/SIGE4/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/DependencyInjection/ContainerAwareHttpKernel.php(69): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#5 /var/www/SIGE4/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(185): Symfony\Component\HttpKernel\DependencyInjection\ContainerAwareHttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#6 /var/www/SIGE4/web/app_dev.php(30): Symfony\Component\HttpKernel\Kernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#7 {main}
 
###############################################################
###############################################################
[2016-07-01 17:45:39]: Symfony\Component\Debug\Exception\ContextErrorException   codigo: 0
  mensaje: Notice: Undefined index: code
  clase: /var/www/SIGE4/src/SIGE/SecurityManagerBundle/Controller/UsuarioController.php
  linea: 140
  metodo: handleError
  traza: #0 /var/www/SIGE4/src/SIGE/SecurityManagerBundle/Controller/UsuarioController.php(140): Symfony\Component\Debug\ErrorHandler->handleError(8, 'Undefined index...', '/var/www/SIGE4/...', 140, Array)
#1 [internal function]: SIGE\SecurityManagerBundle\Controller\UsuarioController->postUsuarioAction(Object(Symfony\Component\HttpFoundation\Request))
#2 /var/www/SIGE4/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php(139): call_user_func_array(Array, Array)
#3 /var/www/SIGE4/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php(62): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1)
#4 /var/www/SIGE4/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/DependencyInjection/ContainerAwareHttpKernel.php(69): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#5 /var/www/SIGE4/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(185): Symfony\Component\HttpKernel\DependencyInjection\ContainerAwareHttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#6 /var/www/SIGE4/web/app_dev.php(30): Symfony\Component\HttpKernel\Kernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#7 {main}
 
###############################################################
###############################################################
[2016-07-01 17:47:29]: Symfony\Component\Debug\Exception\ContextErrorException   codigo: 0
  mensaje: Notice: Undefined index: success
  clase: /var/www/SIGE4/src/SIGE/SecurityManagerBundle/Controller/UsuarioController.php
  linea: 186
  metodo: handleError
  traza: #0 /var/www/SIGE4/src/SIGE/SecurityManagerBundle/Controller/UsuarioController.php(186): Symfony\Component\Debug\ErrorHandler->handleError(8, 'Undefined index...', '/var/www/SIGE4/...', 186, Array)
#1 [internal function]: SIGE\SecurityManagerBundle\Controller\UsuarioController->putUsuarioAction(Object(Symfony\Component\HttpFoundation\Request), '8')
#2 /var/www/SIGE4/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php(139): call_user_func_array(Array, Array)
#3 /var/www/SIGE4/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php(62): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1)
#4 /var/www/SIGE4/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/DependencyInjection/ContainerAwareHttpKernel.php(69): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#5 /var/www/SIGE4/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(185): Symfony\Component\HttpKernel\DependencyInjection\ContainerAwareHttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#6 /var/www/SIGE4/web/app_dev.php(30): Symfony\Component\HttpKernel\Kernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#7 {main}
 
###############################################################
###############################################################
[2016-07-04 14:50:36]: Symfony\Component\Debug\Exception\ContextErrorException   codigo: 0
  mensaje: Notice: Undefined index: success
  clase: /var/www/SIGE4/src/SIGE/SecurityManagerBundle/Controller/UsuarioController.php
  linea: 186
  metodo: handleError
  traza: #0 /var/www/SIGE4/src/SIGE/SecurityManagerBundle/Controller/UsuarioController.php(186): Symfony\Component\Debug\ErrorHandler->handleError(8, 'Undefined index...', '/var/www/SIGE4/...', 186, Array)
#1 [internal function]: SIGE\SecurityManagerBundle\Controller\UsuarioController->putUsuarioAction(Object(Symfony\Component\HttpFoundation\Request), '9')
#2 /var/www/SIGE4/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php(139): call_user_func_array(Array, Array)
#3 /var/www/SIGE4/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php(62): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1)
#4 /var/www/SIGE4/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/DependencyInjection/ContainerAwareHttpKernel.php(69): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#5 /var/www/SIGE4/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(185): Symfony\Component\HttpKernel\DependencyInjection\ContainerAwareHttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#6 /var/www/SIGE4/web/app_dev.php(30): Symfony\Component\HttpKernel\Kernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#7 {main}
 
###############################################################
###############################################################
[2016-07-04 14:52:14]: Symfony\Component\Debug\Exception\ContextErrorException   codigo: 0
  mensaje: Notice: Undefined index: success
  clase: /var/www/SIGE4/src/SIGE/SecurityManagerBundle/Controller/UsuarioController.php
  linea: 186
  metodo: handleError
  traza: #0 /var/www/SIGE4/src/SIGE/SecurityManagerBundle/Controller/UsuarioController.php(186): Symfony\Component\Debug\ErrorHandler->handleError(8, 'Undefined index...', '/var/www/SIGE4/...', 186, Array)
#1 [internal function]: SIGE\SecurityManagerBundle\Controller\UsuarioController->putUsuarioAction(Object(Symfony\Component\HttpFoundation\Request), '9')
#2 /var/www/SIGE4/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php(139): call_user_func_array(Array, Array)
#3 /var/www/SIGE4/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php(62): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1)
#4 /var/www/SIGE4/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/DependencyInjection/ContainerAwareHttpKernel.php(69): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#5 /var/www/SIGE4/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(185): Symfony\Component\HttpKernel\DependencyInjection\ContainerAwareHttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#6 /var/www/SIGE4/web/app_dev.php(30): Symfony\Component\HttpKernel\Kernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#7 {main}
 
###############################################################
###############################################################
[2016-07-04 14:54:07]: Symfony\Component\Debug\Exception\ContextErrorException   codigo: 0
  mensaje: Notice: Undefined index: success
  clase: /var/www/SIGE4/src/SIGE/SecurityManagerBundle/Controller/UsuarioController.php
  linea: 186
  metodo: handleError
  traza: #0 /var/www/SIGE4/src/SIGE/SecurityManagerBundle/Controller/UsuarioController.php(186): Symfony\Component\Debug\ErrorHandler->handleError(8, 'Undefined index...', '/var/www/SIGE4/...', 186, Array)
#1 [internal function]: SIGE\SecurityManagerBundle\Controller\UsuarioController->putUsuarioAction(Object(Symfony\Component\HttpFoundation\Request), '9')
#2 /var/www/SIGE4/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php(139): call_user_func_array(Array, Array)
#3 /var/www/SIGE4/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php(62): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1)
#4 /var/www/SIGE4/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/DependencyInjection/ContainerAwareHttpKernel.php(69): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#5 /var/www/SIGE4/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(185): Symfony\Component\HttpKernel\DependencyInjection\ContainerAwareHttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#6 /var/www/SIGE4/web/app_dev.php(30): Symfony\Component\HttpKernel\Kernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#7 {main}
 
###############################################################
###############################################################
[2016-07-04 14:56:48]: Symfony\Component\Debug\Exception\ContextErrorException   codigo: 0
  mensaje: Notice: Undefined index: success
  clase: /var/www/SIGE4/src/SIGE/SecurityManagerBundle/Controller/UsuarioController.php
  linea: 186
  metodo: handleError
  traza: #0 /var/www/SIGE4/src/SIGE/SecurityManagerBundle/Controller/UsuarioController.php(186): Symfony\Component\Debug\ErrorHandler->handleError(8, 'Undefined index...', '/var/www/SIGE4/...', 186, Array)
#1 [internal function]: SIGE\SecurityManagerBundle\Controller\UsuarioController->putUsuarioAction(Object(Symfony\Component\HttpFoundation\Request), '9')
#2 /var/www/SIGE4/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php(139): call_user_func_array(Array, Array)
#3 /var/www/SIGE4/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php(62): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1)
#4 /var/www/SIGE4/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/DependencyInjection/ContainerAwareHttpKernel.php(69): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#5 /var/www/SIGE4/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(185): Symfony\Component\HttpKernel\DependencyInjection\ContainerAwareHttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#6 /var/www/SIGE4/web/app_dev.php(30): Symfony\Component\HttpKernel\Kernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#7 {main}
 
###############################################################
###############################################################
[2016-07-04 14:58:03]: Symfony\Component\Debug\Exception\ContextErrorException   codigo: 0
  mensaje: Notice: Undefined index: success
  clase: /var/www/SIGE4/src/SIGE/SecurityManagerBundle/Controller/UsuarioController.php
  linea: 186
  metodo: handleError
  traza: #0 /var/www/SIGE4/src/SIGE/SecurityManagerBundle/Controller/UsuarioController.php(186): Symfony\Component\Debug\ErrorHandler->handleError(8, 'Undefined index...', '/var/www/SIGE4/...', 186, Array)
#1 [internal function]: SIGE\SecurityManagerBundle\Controller\UsuarioController->putUsuarioAction(Object(Symfony\Component\HttpFoundation\Request), '9')
#2 /var/www/SIGE4/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php(139): call_user_func_array(Array, Array)
#3 /var/www/SIGE4/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php(62): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1)
#4 /var/www/SIGE4/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/DependencyInjection/ContainerAwareHttpKernel.php(69): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#5 /var/www/SIGE4/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(185): Symfony\Component\HttpKernel\DependencyInjection\ContainerAwareHttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#6 /var/www/SIGE4/web/app_dev.php(30): Symfony\Component\HttpKernel\Kernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#7 {main}
 
###############################################################
###############################################################
[2016-07-04 15:01:17]: Symfony\Component\Debug\Exception\ContextErrorException   codigo: 0
  mensaje: Notice: Undefined index: success
  clase: /var/www/SIGE4/src/SIGE/SecurityManagerBundle/Controller/UsuarioController.php
  linea: 186
  metodo: handleError
  traza: #0 /var/www/SIGE4/src/SIGE/SecurityManagerBundle/Controller/UsuarioController.php(186): Symfony\Component\Debug\ErrorHandler->handleError(8, 'Undefined index...', '/var/www/SIGE4/...', 186, Array)
#1 [internal function]: SIGE\SecurityManagerBundle\Controller\UsuarioController->putUsuarioAction(Object(Symfony\Component\HttpFoundation\Request), '9')
#2 /var/www/SIGE4/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php(139): call_user_func_array(Array, Array)
#3 /var/www/SIGE4/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php(62): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1)
#4 /var/www/SIGE4/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/DependencyInjection/ContainerAwareHttpKernel.php(69): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#5 /var/www/SIGE4/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(185): Symfony\Component\HttpKernel\DependencyInjection\ContainerAwareHttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#6 /var/www/SIGE4/web/app_dev.php(30): Symfony\Component\HttpKernel\Kernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#7 {main}
 
###############################################################
###############################################################
[2016-07-04 15:29:22]: Symfony\Component\Debug\Exception\ContextErrorException   codigo: 0
  mensaje: Notice: Undefined index: success
  clase: /var/www/SIGE4/src/SIGE/SecurityManagerBundle/Controller/UsuarioController.php
  linea: 186
  metodo: handleError
  traza: #0 /var/www/SIGE4/src/SIGE/SecurityManagerBundle/Controller/UsuarioController.php(186): Symfony\Component\Debug\ErrorHandler->handleError(8, 'Undefined index...', '/var/www/SIGE4/...', 186, Array)
#1 [internal function]: SIGE\SecurityManagerBundle\Controller\UsuarioController->putUsuarioAction(Object(Symfony\Component\HttpFoundation\Request), '9')
#2 /var/www/SIGE4/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php(139): call_user_func_array(Array, Array)
#3 /var/www/SIGE4/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php(62): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1)
#4 /var/www/SIGE4/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/DependencyInjection/ContainerAwareHttpKernel.php(69): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#5 /var/www/SIGE4/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(185): Symfony\Component\HttpKernel\DependencyInjection\ContainerAwareHttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#6 /var/www/SIGE4/web/app_dev.php(30): Symfony\Component\HttpKernel\Kernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#7 {main}
 
###############################################################
###############################################################
[2016-07-04 17:10:40]: Symfony\Component\Debug\Exception\FatalErrorException   codigo: 0
  mensaje: Compile Error: Cannot use SIGE\SigeBundle\HandlerRest\HttpCode as HttpCode because the name is already in use
  clase: /var/www/SIGE4/src/SIGE/RecordsClassifiersBundle/Controller/AspectoController.php
  linea: 23
  metodo: loadClass
  traza: #0 /var/www/SIGE4/vendor/symfony/symfony/src/Symfony/Component/Routing/Loader/AnnotationDirectoryLoader.php(52): Symfony\Component\Debug\DebugClassLoader->loadClass('')
#1 /var/www/SIGE4/vendor/symfony/symfony/src/Symfony/Component/Routing/Loader/AnnotationDirectoryLoader.php(52): spl_autoload_call('')
#2 /var/www/SIGE4/vendor/symfony/symfony/src/Symfony/Component/Routing/Loader/AnnotationDirectoryLoader.php(52): ReflectionClass->__construct('')
#3 /var/www/SIGE4/vendor/symfony/symfony/src/Symfony/Component/Config/Loader/FileLoader.php(112): Symfony\Component\Routing\Loader\AnnotationDirectoryLoader->load('', '')
#4 /var/www/SIGE4/vendor/symfony/symfony/src/Symfony/Component/Routing/Loader/YamlFileLoader.php(174): Symfony\Component\Config\Loader\FileLoader->import('', '', '', '')
#5 /var/www/SIGE4/vendor/symfony/symfony/src/Symfony/Component/Routing/Loader/YamlFileLoader.php(94): Symfony\Component\Routing\Loader\YamlFileLoader->parseImport('', '', '', '')
#6 /var/www/SIGE4/vendor/symfony/symfony/src/Symfony/Component/Config/Loader/FileLoader.php(112): Symfony\Component\Routing\Loader\YamlFileLoader->load('', '')
#7 /var/www/SIGE4/vendor/symfony/symfony/src/Symfony/Component/Routing/Loader/YamlFileLoader.php(174): Symfony\Component\Config\Loader\FileLoader->import('', '', '', '')
#8 /var/www/SIGE4/vendor/symfony/symfony/src/Symfony/Component/Routing/Loader/YamlFileLoader.php(94): Symfony\Component\Routing\Loader\YamlFileLoader->parseImport('', '', '', '')
#9 /var/www/SIGE4/vendor/symfony/symfony/src/Symfony/Component/Config/Loader/FileLoader.php(112): Symfony\Component\Routing\Loader\YamlFileLoader->load('', '')
#10 /var/www/SIGE4/vendor/symfony/symfony/src/Symfony/Component/Routing/Loader/YamlFileLoader.php(174): Symfony\Component\Config\Loader\FileLoader->import('', '', '', '')
#11 /var/www/SIGE4/vendor/symfony/symfony/src/Symfony/Component/Routing/Loader/YamlFileLoader.php(94): Symfony\Component\Routing\Loader\YamlFileLoader->parseImport('', '', '', '')
#12 /var/www/SIGE4/vendor/symfony/symfony/src/Symfony/Component/Config/Loader/DelegatingLoader.php(45): Symfony\Component\Routing\Loader\YamlFileLoader->load('', '')
#13 /var/www/SIGE4/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Routing/DelegatingLoader.php(83): Symfony\Component\Config\Loader\DelegatingLoader->load('', '')
#14 /var/www/SIGE4/app/cache/dev/classes.php(1589): Symfony\Bundle\FrameworkBundle\Routing\DelegatingLoader->load('', '')
#15 /var/www/SIGE4/app/cache/dev/classes.php(1370): Symfony\Bundle\FrameworkBundle\Routing\Router->getRouteCollection()
#16 /var/www/SIGE4/app/cache/dev/classes.php(1320): Symfony\Component\Routing\Router->getMatcherDumperInstance()
#17 /var/www/SIGE4/vendor/symfony/symfony/src/Symfony/Component/Config/ResourceCheckerConfigCacheFactory.php(46): Symfony\Component\Routing\Router->Symfony\Component\Routing\{closure}('')
#18 /var/www/SIGE4/vendor/symfony/symfony/src/Symfony/Component/Config/ResourceCheckerConfigCacheFactory.php(46): call_user_func:{/var/www/SIGE4/vendor/symfony/symfony/src/Symfony/Component/Config/ResourceCheckerConfigCacheFactory.php:46}('', '')
#19 /var/www/SIGE4/app/cache/dev/classes.php(1330): Symfony\Component\Config\ResourceCheckerConfigCacheFactory->cache('', '')
#20 /var/www/SIGE4/app/cache/dev/classes.php(1294): Symfony\Component\Routing\Router->getMatcher()
#21 /var/www/SIGE4/app/cache/dev/classes.php(2086): Symfony\Component\Routing\Router->matchRequest('')
#22 /var/www/SIGE4/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/Debug/WrappedListener.php(61): Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest('', '', '')
#23 /var/www/SIGE4/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/Debug/WrappedListener.php(61): call_user_func:{/var/www/SIGE4/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/Debug/WrappedListener.php:61}('', '', '', '')
#24 /var/www/SIGE4/app/cache/dev/classes.php(1858): Symfony\Component\EventDispatcher\Debug\WrappedListener->__invoke('', '', '')
#25 /var/www/SIGE4/app/cache/dev/classes.php(1858): call_user_func:{/var/www/SIGE4/app/cache/dev/classes.php:1858}('', '', '', '')
#26 /var/www/SIGE4/app/cache/dev/classes.php(1773): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch('', '', '')
#27 /var/www/SIGE4/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/Debug/TraceableEventDispatcher.php(140): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('', '')
#28 /var/www/SIGE4/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php(120): Symfony\Component\EventDispatcher\Debug\TraceableEventDispatcher->dispatch('', '')
#29 /var/www/SIGE4/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php(62): Symfony\Component\HttpKernel\HttpKernel->handleRaw('', '')
#30 /var/www/SIGE4/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/DependencyInjection/ContainerAwareHttpKernel.php(69): Symfony\Component\HttpKernel\HttpKernel->handle('', '', '')
#31 /var/www/SIGE4/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(185): Symfony\Component\HttpKernel\DependencyInjection\ContainerAwareHttpKernel->handle('', '', '')
#32 /var/www/SIGE4/web/app_dev.php(30): Symfony\Component\HttpKernel\Kernel->handle('', '', '')
#33 /var/www/SIGE4/web/app_dev.php(0): {main}()
#34 {main}
 
###############################################################
###############################################################
[2016-07-04 22:39:54]: Symfony\Component\Debug\Exception\FatalErrorException   codigo: 0
  mensaje: Error: Cannot use object of type Symfony\Component\HttpFoundation\Response as array
  clase: /var/www/SIGE4/src/SIGE/RecordsClassifiersBundle/Controller/AspectoController.php
  linea: 279
  metodo: deleteAspectosAction
  traza: #0 /var/www/SIGE4/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php(139): SIGE\RecordsClassifiersBundle\Controller\AspectoController->deleteAspectosAction('')
#1 /var/www/SIGE4/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php(139): call_user_func_array:{/var/www/SIGE4/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php:139}('', '')
#2 /var/www/SIGE4/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php(62): Symfony\Component\HttpKernel\HttpKernel->handleRaw('', '')
#3 /var/www/SIGE4/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/DependencyInjection/ContainerAwareHttpKernel.php(69): Symfony\Component\HttpKernel\HttpKernel->handle('', '', '')
#4 /var/www/SIGE4/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(185): Symfony\Component\HttpKernel\DependencyInjection\ContainerAwareHttpKernel->handle('', '', '')
#5 /var/www/SIGE4/web/app_dev.php(30): Symfony\Component\HttpKernel\Kernel->handle('', '', '')
#6 /var/www/SIGE4/web/app_dev.php(0): {main}()
#7 {main}
 
###############################################################
###############################################################
[2016-09-05 16:50:58]: LocalException   codigo: S4
  mensaje: Usted no posee permisos para acceder al recurso NomencladorSeguridad
  descripcion: Se lanza la excepción cuando el usuario no posee permisos para acceder al recurso
  clase: /var/www/SIGE4/src/SIGE/SigeBundle/HandlerRest/ClassHandler.php
  linea: 194
  metodo: all
  traza: #0 /var/www/SIGE4/src/SIGE/SecurityManagerBundle/Controller/AppController.php(269): SIGE\SigeBundle\HandlerRest\ClassHandler->all('SIGE\\SecurityMa...', '', false)
#1 /var/www/SIGE4/src/SIGE/SecurityManagerBundle/Controller/AppController.php(84): SIGE\SecurityManagerBundle\Controller\AppController->getAccessAuthRoleAdmin()
#2 [internal function]: SIGE\SecurityManagerBundle\Controller\AppController->getAppsAction(Object(Symfony\Component\HttpFoundation\Request), Object(FOS\RestBundle\Request\ParamFetcher))
#3 /var/www/SIGE4/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php(139): call_user_func_array(Array, Array)
#4 /var/www/SIGE4/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php(62): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1)
#5 /var/www/SIGE4/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/DependencyInjection/ContainerAwareHttpKernel.php(69): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#6 /var/www/SIGE4/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(185): Symfony\Component\HttpKernel\DependencyInjection\ContainerAwareHttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#7 /var/www/SIGE4/web/app_dev.php(30): Symfony\Component\HttpKernel\Kernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#8 {main}
 
###############################################################
###############################################################
[2016-09-05 16:51:36]: LocalException   codigo: S4
  mensaje: Usted no posee permisos para acceder al recurso NomencladorSeguridad
  descripcion: Se lanza la excepción cuando el usuario no posee permisos para acceder al recurso
  clase: /var/www/SIGE4/src/SIGE/SigeBundle/HandlerRest/ClassHandler.php
  linea: 194
  metodo: all
  traza: #0 /var/www/SIGE4/src/SIGE/SecurityManagerBundle/Controller/AppController.php(269): SIGE\SigeBundle\HandlerRest\ClassHandler->all('SIGE\\SecurityMa...', '', false)
#1 /var/www/SIGE4/src/SIGE/SecurityManagerBundle/Controller/AppController.php(84): SIGE\SecurityManagerBundle\Controller\AppController->getAccessAuthRoleAdmin()
#2 [internal function]: SIGE\SecurityManagerBundle\Controller\AppController->getAppsAction(Object(Symfony\Component\HttpFoundation\Request), Object(FOS\RestBundle\Request\ParamFetcher))
#3 /var/www/SIGE4/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php(139): call_user_func_array(Array, Array)
#4 /var/www/SIGE4/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php(62): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1)
#5 /var/www/SIGE4/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/DependencyInjection/ContainerAwareHttpKernel.php(69): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#6 /var/www/SIGE4/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(185): Symfony\Component\HttpKernel\DependencyInjection\ContainerAwareHttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#7 /var/www/SIGE4/web/app_dev.php(30): Symfony\Component\HttpKernel\Kernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#8 {main}
 
###############################################################
###############################################################
[2016-09-05 16:52:48]: LocalException   codigo: S4
  mensaje: Usted no posee permisos para acceder al recurso NomencladorSeguridad
  descripcion: Se lanza la excepción cuando el usuario no posee permisos para acceder al recurso
  clase: /var/www/SIGE4/src/SIGE/SigeBundle/HandlerRest/ClassHandler.php
  linea: 194
  metodo: all
  traza: #0 /var/www/SIGE4/src/SIGE/SecurityManagerBundle/Controller/AppController.php(269): SIGE\SigeBundle\HandlerRest\ClassHandler->all('SIGE\\SecurityMa...', '', false)
#1 /var/www/SIGE4/src/SIGE/SecurityManagerBundle/Controller/AppController.php(84): SIGE\SecurityManagerBundle\Controller\AppController->getAccessAuthRoleAdmin()
#2 [internal function]: SIGE\SecurityManagerBundle\Controller\AppController->getAppsAction(Object(Symfony\Component\HttpFoundation\Request), Object(FOS\RestBundle\Request\ParamFetcher))
#3 /var/www/SIGE4/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php(139): call_user_func_array(Array, Array)
#4 /var/www/SIGE4/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php(62): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1)
#5 /var/www/SIGE4/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/DependencyInjection/ContainerAwareHttpKernel.php(69): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#6 /var/www/SIGE4/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(185): Symfony\Component\HttpKernel\DependencyInjection\ContainerAwareHttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#7 /var/www/SIGE4/web/app_dev.php(30): Symfony\Component\HttpKernel\Kernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#8 {main}
 
###############################################################
###############################################################
[2016-09-05 16:53:24]: LocalException   codigo: S4
  mensaje: Usted no posee permisos para acceder al recurso NomencladorSeguridad
  descripcion: Se lanza la excepción cuando el usuario no posee permisos para acceder al recurso
  clase: /var/www/SIGE4/src/SIGE/SigeBundle/HandlerRest/ClassHandler.php
  linea: 194
  metodo: all
  traza: #0 /var/www/SIGE4/src/SIGE/SecurityManagerBundle/Controller/AppController.php(269): SIGE\SigeBundle\HandlerRest\ClassHandler->all('SIGE\\SecurityMa...', '', false)
#1 /var/www/SIGE4/src/SIGE/SecurityManagerBundle/Controller/AppController.php(84): SIGE\SecurityManagerBundle\Controller\AppController->getAccessAuthRoleAdmin()
#2 [internal function]: SIGE\SecurityManagerBundle\Controller\AppController->getAppsAction(Object(Symfony\Component\HttpFoundation\Request), Object(FOS\RestBundle\Request\ParamFetcher))
#3 /var/www/SIGE4/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php(139): call_user_func_array(Array, Array)
#4 /var/www/SIGE4/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php(62): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1)
#5 /var/www/SIGE4/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/DependencyInjection/ContainerAwareHttpKernel.php(69): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#6 /var/www/SIGE4/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(185): Symfony\Component\HttpKernel\DependencyInjection\ContainerAwareHttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#7 /var/www/SIGE4/web/app_dev.php(30): Symfony\Component\HttpKernel\Kernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#8 {main}
 
###############################################################
###############################################################
[2016-09-05 16:58:20]: LocalException   codigo: S4
  mensaje: Usted no posee permisos para acceder al recurso NomencladorSeguridad
  descripcion: Se lanza la excepción cuando el usuario no posee permisos para acceder al recurso
  clase: /var/www/SIGE4/src/SIGE/SigeBundle/HandlerRest/ClassHandler.php
  linea: 194
  metodo: all
  traza: #0 /var/www/SIGE4/src/SIGE/SecurityManagerBundle/Controller/AppController.php(269): SIGE\SigeBundle\HandlerRest\ClassHandler->all('SIGE\\SecurityMa...', '', false)
#1 /var/www/SIGE4/src/SIGE/SecurityManagerBundle/Controller/AppController.php(84): SIGE\SecurityManagerBundle\Controller\AppController->getAccessAuthRoleAdmin()
#2 [internal function]: SIGE\SecurityManagerBundle\Controller\AppController->getAppsAction(Object(Symfony\Component\HttpFoundation\Request), Object(FOS\RestBundle\Request\ParamFetcher))
#3 /var/www/SIGE4/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php(139): call_user_func_array(Array, Array)
#4 /var/www/SIGE4/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php(62): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1)
#5 /var/www/SIGE4/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/DependencyInjection/ContainerAwareHttpKernel.php(69): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#6 /var/www/SIGE4/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(185): Symfony\Component\HttpKernel\DependencyInjection\ContainerAwareHttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#7 /var/www/SIGE4/web/app_dev.php(30): Symfony\Component\HttpKernel\Kernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#8 {main}
 
###############################################################
###############################################################
[2016-09-05 16:58:25]: LocalException   codigo: S4
  mensaje: Usted no posee permisos para acceder al recurso NomencladorSeguridad
  descripcion: Se lanza la excepción cuando el usuario no posee permisos para acceder al recurso
  clase: /var/www/SIGE4/src/SIGE/SigeBundle/HandlerRest/ClassHandler.php
  linea: 194
  metodo: all
  traza: #0 /var/www/SIGE4/src/SIGE/SecurityManagerBundle/Controller/AppController.php(269): SIGE\SigeBundle\HandlerRest\ClassHandler->all('SIGE\\SecurityMa...', '', false)
#1 /var/www/SIGE4/src/SIGE/SecurityManagerBundle/Controller/AppController.php(84): SIGE\SecurityManagerBundle\Controller\AppController->getAccessAuthRoleAdmin()
#2 [internal function]: SIGE\SecurityManagerBundle\Controller\AppController->getAppsAction(Object(Symfony\Component\HttpFoundation\Request), Object(FOS\RestBundle\Request\ParamFetcher))
#3 /var/www/SIGE4/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php(139): call_user_func_array(Array, Array)
#4 /var/www/SIGE4/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php(62): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1)
#5 /var/www/SIGE4/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/DependencyInjection/ContainerAwareHttpKernel.php(69): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#6 /var/www/SIGE4/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(185): Symfony\Component\HttpKernel\DependencyInjection\ContainerAwareHttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#7 /var/www/SIGE4/web/app_dev.php(30): Symfony\Component\HttpKernel\Kernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#8 {main}
 
###############################################################
###############################################################
[2016-09-05 16:58:44]: LocalException   codigo: S4
  mensaje: Usted no posee permisos para acceder al recurso NomencladorSeguridad
  descripcion: Se lanza la excepción cuando el usuario no posee permisos para acceder al recurso
  clase: /var/www/SIGE4/src/SIGE/SigeBundle/HandlerRest/ClassHandler.php
  linea: 194
  metodo: all
  traza: #0 /var/www/SIGE4/src/SIGE/SecurityManagerBundle/Controller/AppController.php(269): SIGE\SigeBundle\HandlerRest\ClassHandler->all('SIGE\\SecurityMa...', '', false)
#1 /var/www/SIGE4/src/SIGE/SecurityManagerBundle/Controller/AppController.php(84): SIGE\SecurityManagerBundle\Controller\AppController->getAccessAuthRoleAdmin()
#2 [internal function]: SIGE\SecurityManagerBundle\Controller\AppController->getAppsAction(Object(Symfony\Component\HttpFoundation\Request), Object(FOS\RestBundle\Request\ParamFetcher))
#3 /var/www/SIGE4/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php(139): call_user_func_array(Array, Array)
#4 /var/www/SIGE4/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php(62): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1)
#5 /var/www/SIGE4/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/DependencyInjection/ContainerAwareHttpKernel.php(69): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#6 /var/www/SIGE4/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(185): Symfony\Component\HttpKernel\DependencyInjection\ContainerAwareHttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#7 /var/www/SIGE4/web/app_dev.php(30): Symfony\Component\HttpKernel\Kernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#8 {main}
 
###############################################################
###############################################################
[2016-09-05 17:00:17]: LocalException   codigo: S4
  mensaje: Usted no posee permisos para acceder al recurso NomencladorSeguridad
  descripcion: Se lanza la excepción cuando el usuario no posee permisos para acceder al recurso
  clase: /var/www/SIGE4/src/SIGE/SigeBundle/HandlerRest/ClassHandler.php
  linea: 194
  metodo: all
  traza: #0 /var/www/SIGE4/src/SIGE/SecurityManagerBundle/Controller/AppController.php(269): SIGE\SigeBundle\HandlerRest\ClassHandler->all('SIGE\\SecurityMa...', '', false)
#1 /var/www/SIGE4/src/SIGE/SecurityManagerBundle/Controller/AppController.php(84): SIGE\SecurityManagerBundle\Controller\AppController->getAccessAuthRoleAdmin()
#2 [internal function]: SIGE\SecurityManagerBundle\Controller\AppController->getAppsAction(Object(Symfony\Component\HttpFoundation\Request), Object(FOS\RestBundle\Request\ParamFetcher))
#3 /var/www/SIGE4/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php(139): call_user_func_array(Array, Array)
#4 /var/www/SIGE4/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php(62): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1)
#5 /var/www/SIGE4/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/DependencyInjection/ContainerAwareHttpKernel.php(69): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#6 /var/www/SIGE4/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(185): Symfony\Component\HttpKernel\DependencyInjection\ContainerAwareHttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#7 /var/www/SIGE4/web/app_dev.php(30): Symfony\Component\HttpKernel\Kernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#8 {main}
 
###############################################################
###############################################################
[2016-09-05 17:00:31]: LocalException   codigo: S4
  mensaje: Usted no posee permisos para acceder al recurso NomencladorSeguridad
  descripcion: Se lanza la excepción cuando el usuario no posee permisos para acceder al recurso
  clase: /var/www/SIGE4/src/SIGE/SigeBundle/HandlerRest/ClassHandler.php
  linea: 194
  metodo: all
  traza: #0 /var/www/SIGE4/src/SIGE/SecurityManagerBundle/Controller/AppController.php(269): SIGE\SigeBundle\HandlerRest\ClassHandler->all('SIGE\\SecurityMa...', '', false)
#1 /var/www/SIGE4/src/SIGE/SecurityManagerBundle/Controller/AppController.php(84): SIGE\SecurityManagerBundle\Controller\AppController->getAccessAuthRoleAdmin()
#2 [internal function]: SIGE\SecurityManagerBundle\Controller\AppController->getAppsAction(Object(Symfony\Component\HttpFoundation\Request), Object(FOS\RestBundle\Request\ParamFetcher))
#3 /var/www/SIGE4/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php(139): call_user_func_array(Array, Array)
#4 /var/www/SIGE4/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php(62): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1)
#5 /var/www/SIGE4/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/DependencyInjection/ContainerAwareHttpKernel.php(69): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#6 /var/www/SIGE4/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(185): Symfony\Component\HttpKernel\DependencyInjection\ContainerAwareHttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#7 /var/www/SIGE4/web/app_dev.php(30): Symfony\Component\HttpKernel\Kernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#8 {main}
 
###############################################################
###############################################################
[2016-09-05 17:02:00]: LocalException   codigo: S4
  mensaje: Usted no posee permisos para acceder al recurso NomencladorSeguridad
  descripcion: Se lanza la excepción cuando el usuario no posee permisos para acceder al recurso
  clase: /var/www/SIGE4/src/SIGE/SigeBundle/HandlerRest/ClassHandler.php
  linea: 194
  metodo: all
  traza: #0 /var/www/SIGE4/src/SIGE/SecurityManagerBundle/Controller/AppController.php(269): SIGE\SigeBundle\HandlerRest\ClassHandler->all('SIGE\\SecurityMa...', '', false)
#1 /var/www/SIGE4/src/SIGE/SecurityManagerBundle/Controller/AppController.php(84): SIGE\SecurityManagerBundle\Controller\AppController->getAccessAuthRoleAdmin()
#2 [internal function]: SIGE\SecurityManagerBundle\Controller\AppController->getAppsAction(Object(Symfony\Component\HttpFoundation\Request), Object(FOS\RestBundle\Request\ParamFetcher))
#3 /var/www/SIGE4/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php(139): call_user_func_array(Array, Array)
#4 /var/www/SIGE4/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php(62): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1)
#5 /var/www/SIGE4/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/DependencyInjection/ContainerAwareHttpKernel.php(69): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#6 /var/www/SIGE4/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(185): Symfony\Component\HttpKernel\DependencyInjection\ContainerAwareHttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#7 /var/www/SIGE4/web/app_dev.php(30): Symfony\Component\HttpKernel\Kernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#8 {main}
 
###############################################################
###############################################################
[2016-09-05 17:03:35]: LocalException   codigo: S4
  mensaje: Usted no posee permisos para acceder al recurso NomencladorSeguridad
  descripcion: Se lanza la excepción cuando el usuario no posee permisos para acceder al recurso
  clase: /var/www/SIGE4/src/SIGE/SigeBundle/HandlerRest/ClassHandler.php
  linea: 194
  metodo: all
  traza: #0 /var/www/SIGE4/src/SIGE/SecurityManagerBundle/Controller/AppController.php(269): SIGE\SigeBundle\HandlerRest\ClassHandler->all('SIGE\\SecurityMa...', '', false)
#1 /var/www/SIGE4/src/SIGE/SecurityManagerBundle/Controller/AppController.php(84): SIGE\SecurityManagerBundle\Controller\AppController->getAccessAuthRoleAdmin()
#2 [internal function]: SIGE\SecurityManagerBundle\Controller\AppController->getAppsAction(Object(Symfony\Component\HttpFoundation\Request), Object(FOS\RestBundle\Request\ParamFetcher))
#3 /var/www/SIGE4/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php(139): call_user_func_array(Array, Array)
#4 /var/www/SIGE4/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php(62): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1)
#5 /var/www/SIGE4/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/DependencyInjection/ContainerAwareHttpKernel.php(69): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#6 /var/www/SIGE4/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(185): Symfony\Component\HttpKernel\DependencyInjection\ContainerAwareHttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#7 /var/www/SIGE4/web/app_dev.php(30): Symfony\Component\HttpKernel\Kernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#8 {main}
 
###############################################################
###############################################################
[2016-09-05 17:03:47]: LocalException   codigo: S4
  mensaje: Usted no posee permisos para acceder al recurso NomencladorSeguridad
  descripcion: Se lanza la excepción cuando el usuario no posee permisos para acceder al recurso
  clase: /var/www/SIGE4/src/SIGE/SigeBundle/HandlerRest/ClassHandler.php
  linea: 194
  metodo: all
  traza: #0 /var/www/SIGE4/src/SIGE/SecurityManagerBundle/Controller/AppController.php(269): SIGE\SigeBundle\HandlerRest\ClassHandler->all('SIGE\\SecurityMa...', '', false)
#1 /var/www/SIGE4/src/SIGE/SecurityManagerBundle/Controller/AppController.php(84): SIGE\SecurityManagerBundle\Controller\AppController->getAccessAuthRoleAdmin()
#2 [internal function]: SIGE\SecurityManagerBundle\Controller\AppController->getAppsAction(Object(Symfony\Component\HttpFoundation\Request), Object(FOS\RestBundle\Request\ParamFetcher))
#3 /var/www/SIGE4/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php(139): call_user_func_array(Array, Array)
#4 /var/www/SIGE4/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php(62): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1)
#5 /var/www/SIGE4/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/DependencyInjection/ContainerAwareHttpKernel.php(69): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#6 /var/www/SIGE4/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(185): Symfony\Component\HttpKernel\DependencyInjection\ContainerAwareHttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#7 /var/www/SIGE4/web/app_dev.php(30): Symfony\Component\HttpKernel\Kernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#8 {main}
 
###############################################################
###############################################################
[2016-09-05 17:03:54]: LocalException   codigo: S4
  mensaje: Usted no posee permisos para acceder al recurso NomencladorSeguridad
  descripcion: Se lanza la excepción cuando el usuario no posee permisos para acceder al recurso
  clase: /var/www/SIGE4/src/SIGE/SigeBundle/HandlerRest/ClassHandler.php
  linea: 194
  metodo: all
  traza: #0 /var/www/SIGE4/src/SIGE/SecurityManagerBundle/Controller/AppController.php(269): SIGE\SigeBundle\HandlerRest\ClassHandler->all('SIGE\\SecurityMa...', '', false)
#1 /var/www/SIGE4/src/SIGE/SecurityManagerBundle/Controller/AppController.php(84): SIGE\SecurityManagerBundle\Controller\AppController->getAccessAuthRoleAdmin()
#2 [internal function]: SIGE\SecurityManagerBundle\Controller\AppController->getAppsAction(Object(Symfony\Component\HttpFoundation\Request), Object(FOS\RestBundle\Request\ParamFetcher))
#3 /var/www/SIGE4/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php(139): call_user_func_array(Array, Array)
#4 /var/www/SIGE4/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php(62): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1)
#5 /var/www/SIGE4/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/DependencyInjection/ContainerAwareHttpKernel.php(69): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#6 /var/www/SIGE4/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(185): Symfony\Component\HttpKernel\DependencyInjection\ContainerAwareHttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#7 /var/www/SIGE4/web/app_dev.php(30): Symfony\Component\HttpKernel\Kernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#8 {main}
 
###############################################################
###############################################################
[2016-09-08 17:37:26]: Symfony\Component\Debug\Exception\ContextErrorException   codigo: 0
  mensaje: Catchable Fatal Error: Argument 4 passed to Symfony\Component\Security\Core\Authentication\Token\UsernamePasswordToken::__construct() must be of the type array, object given, called in /var/www/SIGE4/vendor/escapestudios/wsse-authentication-bundle/Escape/WSSEAuthenticationBundle/Security/Core/Authentication/Provider/Provider.php on line 88 and defined
  clase: /var/www/SIGE4/vendor/symfony/symfony/src/Symfony/Component/Security/Core/Authentication/Token/UsernamePasswordToken.php
  linea: 36
  metodo: handleError
  traza: #0 /var/www/SIGE4/vendor/symfony/symfony/src/Symfony/Component/Security/Core/Authentication/Token/UsernamePasswordToken.php(36): Symfony\Component\Debug\ErrorHandler->handleError(4096, 'Argument 4 pass...', '/var/www/SIGE4/...', 36, Array)
#1 /var/www/SIGE4/vendor/escapestudios/wsse-authentication-bundle/Escape/WSSEAuthenticationBundle/Security/Core/Authentication/Provider/Provider.php(88): Symfony\Component\Security\Core\Authentication\Token\UsernamePasswordToken->__construct(Object(SIGE\SecurityManagerBundle\Entity\Usuario), '123', 'wsse_secured', Object(Doctrine\ORM\PersistentCollection))
#2 /var/www/SIGE4/app/cache/dev/classes.php(2676): Escape\WSSEAuthenticationBundle\Security\Core\Authentication\Provider\Provider->authenticate(Object(Symfony\Component\Security\Core\Authentication\Token\UsernamePasswordToken))
#3 /var/www/SIGE4/vendor/escapestudios/wsse-authentication-bundle/Escape/WSSEAuthenticationBundle/Security/Http/Firewall/Listener.php(90): Symfony\Component\Security\Core\Authentication\AuthenticationProviderManager->authenticate(Object(Symfony\Component\Security\Core\Authentication\Token\UsernamePasswordToken))
#4 /var/www/SIGE4/app/cache/dev/classes.php(2591): Escape\WSSEAuthenticationBundle\Security\Http\Firewall\Listener->handle(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent))
#5 [internal function]: Symfony\Component\Security\Http\Firewall->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\HttpKernel\Debug\TraceableEventDispatcher))
#6 /var/www/SIGE4/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/Debug/WrappedListener.php(61): call_user_func(Array, Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\HttpKernel\Debug\TraceableEventDispatcher))
#7 [internal function]: Symfony\Component\EventDispatcher\Debug\WrappedListener->__invoke(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\ContainerAwareEventDispatcher))
#8 /var/www/SIGE4/app/cache/dev/classes.php(1858): call_user_func(Object(Symfony\Component\EventDispatcher\Debug\WrappedListener), Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\ContainerAwareEventDispatcher))
#9 /var/www/SIGE4/app/cache/dev/classes.php(1773): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent))
#10 /var/www/SIGE4/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/Debug/TraceableEventDispatcher.php(140): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent))
#11 /var/www/SIGE4/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php(120): Symfony\Component\EventDispatcher\Debug\TraceableEventDispatcher->dispatch('kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent))
#12 /var/www/SIGE4/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php(62): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1)
#13 /var/www/SIGE4/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/DependencyInjection/ContainerAwareHttpKernel.php(69): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#14 /var/www/SIGE4/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(185): Symfony\Component\HttpKernel\DependencyInjection\ContainerAwareHttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#15 /var/www/SIGE4/web/app_dev.php(30): Symfony\Component\HttpKernel\Kernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#16 {main}
 
###############################################################
###############################################################
[2016-09-08 17:43:40]: Symfony\Component\Debug\Exception\ContextErrorException   codigo: 0
  mensaje: Catchable Fatal Error: Argument 4 passed to Symfony\Component\Security\Core\Authentication\Token\UsernamePasswordToken::__construct() must be of the type array, object given, called in /var/www/SIGE4/vendor/escapestudios/wsse-authentication-bundle/Escape/WSSEAuthenticationBundle/Security/Core/Authentication/Provider/Provider.php on line 76 and defined
  clase: /var/www/SIGE4/vendor/symfony/symfony/src/Symfony/Component/Security/Core/Authentication/Token/UsernamePasswordToken.php
  linea: 36
  metodo: handleError
  traza: #0 /var/www/SIGE4/vendor/symfony/symfony/src/Symfony/Component/Security/Core/Authentication/Token/UsernamePasswordToken.php(36): Symfony\Component\Debug\ErrorHandler->handleError(4096, 'Argument 4 pass...', '/var/www/SIGE4/...', 36, Array)
#1 /var/www/SIGE4/vendor/escapestudios/wsse-authentication-bundle/Escape/WSSEAuthenticationBundle/Security/Core/Authentication/Provider/Provider.php(76): Symfony\Component\Security\Core\Authentication\Token\UsernamePasswordToken->__construct(Object(SIGE\SecurityManagerBundle\Entity\Usuario), '123', 'wsse_secured', Object(Doctrine\ORM\PersistentCollection))
#2 /var/www/SIGE4/app/cache/dev/classes.php(2676): Escape\WSSEAuthenticationBundle\Security\Core\Authentication\Provider\Provider->authenticate(Object(Symfony\Component\Security\Core\Authentication\Token\UsernamePasswordToken))
#3 /var/www/SIGE4/vendor/escapestudios/wsse-authentication-bundle/Escape/WSSEAuthenticationBundle/Security/Http/Firewall/Listener.php(90): Symfony\Component\Security\Core\Authentication\AuthenticationProviderManager->authenticate(Object(Symfony\Component\Security\Core\Authentication\Token\UsernamePasswordToken))
#4 /var/www/SIGE4/app/cache/dev/classes.php(2591): Escape\WSSEAuthenticationBundle\Security\Http\Firewall\Listener->handle(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent))
#5 [internal function]: Symfony\Component\Security\Http\Firewall->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\HttpKernel\Debug\TraceableEventDispatcher))
#6 /var/www/SIGE4/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/Debug/WrappedListener.php(61): call_user_func(Array, Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\HttpKernel\Debug\TraceableEventDispatcher))
#7 [internal function]: Symfony\Component\EventDispatcher\Debug\WrappedListener->__invoke(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\ContainerAwareEventDispatcher))
#8 /var/www/SIGE4/app/cache/dev/classes.php(1858): call_user_func(Object(Symfony\Component\EventDispatcher\Debug\WrappedListener), Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\ContainerAwareEventDispatcher))
#9 /var/www/SIGE4/app/cache/dev/classes.php(1773): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent))
#10 /var/www/SIGE4/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/Debug/TraceableEventDispatcher.php(140): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent))
#11 /var/www/SIGE4/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php(120): Symfony\Component\EventDispatcher\Debug\TraceableEventDispatcher->dispatch('kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent))
#12 /var/www/SIGE4/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php(62): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1)
#13 /var/www/SIGE4/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/DependencyInjection/ContainerAwareHttpKernel.php(69): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#14 /var/www/SIGE4/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(185): Symfony\Component\HttpKernel\DependencyInjection\ContainerAwareHttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#15 /var/www/SIGE4/web/app_dev.php(30): Symfony\Component\HttpKernel\Kernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#16 {main}
 
###############################################################
###############################################################
[2016-09-08 17:44:57]: Symfony\Component\Debug\Exception\ContextErrorException   codigo: 0
  mensaje: Catchable Fatal Error: Argument 4 passed to Symfony\Component\Security\Core\Authentication\Token\UsernamePasswordToken::__construct() must be of the type array, object given, called in /var/www/SIGE4/vendor/escapestudios/wsse-authentication-bundle/Escape/WSSEAuthenticationBundle/Security/Core/Authentication/Provider/Provider.php on line 76 and defined
  clase: /var/www/SIGE4/vendor/symfony/symfony/src/Symfony/Component/Security/Core/Authentication/Token/UsernamePasswordToken.php
  linea: 36
  metodo: handleError
  traza: #0 /var/www/SIGE4/vendor/symfony/symfony/src/Symfony/Component/Security/Core/Authentication/Token/UsernamePasswordToken.php(36): Symfony\Component\Debug\ErrorHandler->handleError(4096, 'Argument 4 pass...', '/var/www/SIGE4/...', 36, Array)
#1 /var/www/SIGE4/vendor/escapestudios/wsse-authentication-bundle/Escape/WSSEAuthenticationBundle/Security/Core/Authentication/Provider/Provider.php(76): Symfony\Component\Security\Core\Authentication\Token\UsernamePasswordToken->__construct(Object(SIGE\SecurityManagerBundle\Entity\Usuario), '123', 'wsse_secured', Object(Doctrine\ORM\PersistentCollection))
#2 /var/www/SIGE4/app/cache/dev/classes.php(2676): Escape\WSSEAuthenticationBundle\Security\Core\Authentication\Provider\Provider->authenticate(Object(Symfony\Component\Security\Core\Authentication\Token\UsernamePasswordToken))
#3 /var/www/SIGE4/vendor/escapestudios/wsse-authentication-bundle/Escape/WSSEAuthenticationBundle/Security/Http/Firewall/Listener.php(90): Symfony\Component\Security\Core\Authentication\AuthenticationProviderManager->authenticate(Object(Symfony\Component\Security\Core\Authentication\Token\UsernamePasswordToken))
#4 /var/www/SIGE4/app/cache/dev/classes.php(2591): Escape\WSSEAuthenticationBundle\Security\Http\Firewall\Listener->handle(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent))
#5 [internal function]: Symfony\Component\Security\Http\Firewall->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\HttpKernel\Debug\TraceableEventDispatcher))
#6 /var/www/SIGE4/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/Debug/WrappedListener.php(61): call_user_func(Array, Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\HttpKernel\Debug\TraceableEventDispatcher))
#7 [internal function]: Symfony\Component\EventDispatcher\Debug\WrappedListener->__invoke(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\ContainerAwareEventDispatcher))
#8 /var/www/SIGE4/app/cache/dev/classes.php(1858): call_user_func(Object(Symfony\Component\EventDispatcher\Debug\WrappedListener), Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\ContainerAwareEventDispatcher))
#9 /var/www/SIGE4/app/cache/dev/classes.php(1773): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent))
#10 /var/www/SIGE4/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/Debug/TraceableEventDispatcher.php(140): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent))
#11 /var/www/SIGE4/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php(120): Symfony\Component\EventDispatcher\Debug\TraceableEventDispatcher->dispatch('kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent))
#12 /var/www/SIGE4/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php(62): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1)
#13 /var/www/SIGE4/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/DependencyInjection/ContainerAwareHttpKernel.php(69): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#14 /var/www/SIGE4/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(185): Symfony\Component\HttpKernel\DependencyInjection\ContainerAwareHttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#15 /var/www/SIGE4/web/app_dev.php(30): Symfony\Component\HttpKernel\Kernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#16 {main}
 
###############################################################
###############################################################
[2016-09-08 17:56:05]: Symfony\Component\Debug\Exception\ContextErrorException   codigo: 0
  mensaje: Catchable Fatal Error: Argument 1 passed to Symfony\Component\HttpKernel\Event\GetResponseEvent::setResponse() must be an instance of Symfony\Component\HttpFoundation\Response, instance of Symfony\Component\Security\Core\Authentication\Token\UsernamePasswordToken given, called in /var/www/SIGE4/vendor/escapestudios/wsse-authentication-bundle/Escape/WSSEAuthenticationBundle/Security/Http/Firewall/Listener.php on line 95 and defined
  clase: /var/www/SIGE4/app/cache/dev/classes.php
  linea: 2342
  metodo: handleError
  traza: #0 /var/www/SIGE4/app/cache/dev/classes.php(2342): Symfony\Component\Debug\ErrorHandler->handleError(4096, 'Argument 1 pass...', '/var/www/SIGE4/...', 2342, Array)
#1 /var/www/SIGE4/vendor/escapestudios/wsse-authentication-bundle/Escape/WSSEAuthenticationBundle/Security/Http/Firewall/Listener.php(95): Symfony\Component\HttpKernel\Event\GetResponseEvent->setResponse(Object(Symfony\Component\Security\Core\Authentication\Token\UsernamePasswordToken))
#2 /var/www/SIGE4/app/cache/dev/classes.php(2591): Escape\WSSEAuthenticationBundle\Security\Http\Firewall\Listener->handle(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent))
#3 [internal function]: Symfony\Component\Security\Http\Firewall->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\HttpKernel\Debug\TraceableEventDispatcher))
#4 /var/www/SIGE4/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/Debug/WrappedListener.php(61): call_user_func(Array, Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\HttpKernel\Debug\TraceableEventDispatcher))
#5 [internal function]: Symfony\Component\EventDispatcher\Debug\WrappedListener->__invoke(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\ContainerAwareEventDispatcher))
#6 /var/www/SIGE4/app/cache/dev/classes.php(1858): call_user_func(Object(Symfony\Component\EventDispatcher\Debug\WrappedListener), Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\ContainerAwareEventDispatcher))
#7 /var/www/SIGE4/app/cache/dev/classes.php(1773): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent))
#8 /var/www/SIGE4/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/Debug/TraceableEventDispatcher.php(140): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent))
#9 /var/www/SIGE4/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php(120): Symfony\Component\EventDispatcher\Debug\TraceableEventDispatcher->dispatch('kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent))
#10 /var/www/SIGE4/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php(62): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1)
#11 /var/www/SIGE4/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/DependencyInjection/ContainerAwareHttpKernel.php(69): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#12 /var/www/SIGE4/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(185): Symfony\Component\HttpKernel\DependencyInjection\ContainerAwareHttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#13 /var/www/SIGE4/web/app_dev.php(30): Symfony\Component\HttpKernel\Kernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#14 {main}
 
###############################################################
###############################################################
[2016-09-08 22:36:08]: Symfony\Component\Debug\Exception\ContextErrorException   codigo: 0
  mensaje: Notice: Undefined variable: token
  clase: /var/www/SIGE4/vendor/escapestudios/wsse-authentication-bundle/Escape/WSSEAuthenticationBundle/Security/Core/Authentication/Provider/Provider.php
  linea: 89
  metodo: handleError
  traza: #0 /var/www/SIGE4/vendor/escapestudios/wsse-authentication-bundle/Escape/WSSEAuthenticationBundle/Security/Core/Authentication/Provider/Provider.php(89): Symfony\Component\Debug\ErrorHandler->handleError(8, 'Undefined varia...', '/var/www/SIGE4/...', 89, Array)
#1 /var/www/SIGE4/vendor/escapestudios/wsse-authentication-bundle/Escape/WSSEAuthenticationBundle/Security/Core/Authentication/Provider/Provider.php(77): Escape\WSSEAuthenticationBundle\Security\Core\Authentication\Provider\Provider->sendResponse(Object(SIGE\SecurityManagerBundle\Entity\Usuario))
#2 /var/www/SIGE4/app/cache/dev/classes.php(2676): Escape\WSSEAuthenticationBundle\Security\Core\Authentication\Provider\Provider->authenticate(Object(Symfony\Component\Security\Core\Authentication\Token\UsernamePasswordToken))
#3 /var/www/SIGE4/vendor/escapestudios/wsse-authentication-bundle/Escape/WSSEAuthenticationBundle/Security/Http/Firewall/Listener.php(93): Symfony\Component\Security\Core\Authentication\AuthenticationProviderManager->authenticate(Object(Symfony\Component\Security\Core\Authentication\Token\UsernamePasswordToken))
#4 /var/www/SIGE4/app/cache/dev/classes.php(2591): Escape\WSSEAuthenticationBundle\Security\Http\Firewall\Listener->handle(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent))
#5 [internal function]: Symfony\Component\Security\Http\Firewall->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\HttpKernel\Debug\TraceableEventDispatcher))
#6 /var/www/SIGE4/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/Debug/WrappedListener.php(61): call_user_func(Array, Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\HttpKernel\Debug\TraceableEventDispatcher))
#7 [internal function]: Symfony\Component\EventDispatcher\Debug\WrappedListener->__invoke(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\ContainerAwareEventDispatcher))
#8 /var/www/SIGE4/app/cache/dev/classes.php(1858): call_user_func(Object(Symfony\Component\EventDispatcher\Debug\WrappedListener), Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\ContainerAwareEventDispatcher))
#9 /var/www/SIGE4/app/cache/dev/classes.php(1773): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent))
#10 /var/www/SIGE4/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/Debug/TraceableEventDispatcher.php(140): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent))
#11 /var/www/SIGE4/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php(120): Symfony\Component\EventDispatcher\Debug\TraceableEventDispatcher->dispatch('kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent))
#12 /var/www/SIGE4/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php(62): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1)
#13 /var/www/SIGE4/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/DependencyInjection/ContainerAwareHttpKernel.php(69): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#14 /var/www/SIGE4/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(185): Symfony\Component\HttpKernel\DependencyInjection\ContainerAwareHttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#15 /var/www/SIGE4/web/app_dev.php(30): Symfony\Component\HttpKernel\Kernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#16 {main}
 
###############################################################
###############################################################
[2016-09-08 22:37:16]: Symfony\Component\Debug\Exception\ContextErrorException   codigo: 0
  mensaje: Notice: Undefined variable: token
  clase: /var/www/SIGE4/vendor/escapestudios/wsse-authentication-bundle/Escape/WSSEAuthenticationBundle/Security/Core/Authentication/Provider/Provider.php
  linea: 89
  metodo: handleError
  traza: #0 /var/www/SIGE4/vendor/escapestudios/wsse-authentication-bundle/Escape/WSSEAuthenticationBundle/Security/Core/Authentication/Provider/Provider.php(89): Symfony\Component\Debug\ErrorHandler->handleError(8, 'Undefined varia...', '/var/www/SIGE4/...', 89, Array)
#1 /var/www/SIGE4/vendor/escapestudios/wsse-authentication-bundle/Escape/WSSEAuthenticationBundle/Security/Core/Authentication/Provider/Provider.php(77): Escape\WSSEAuthenticationBundle\Security\Core\Authentication\Provider\Provider->sendResponse(Object(SIGE\SecurityManagerBundle\Entity\Usuario))
#2 /var/www/SIGE4/app/cache/dev/classes.php(2676): Escape\WSSEAuthenticationBundle\Security\Core\Authentication\Provider\Provider->authenticate(Object(Symfony\Component\Security\Core\Authentication\Token\UsernamePasswordToken))
#3 /var/www/SIGE4/vendor/escapestudios/wsse-authentication-bundle/Escape/WSSEAuthenticationBundle/Security/Http/Firewall/Listener.php(93): Symfony\Component\Security\Core\Authentication\AuthenticationProviderManager->authenticate(Object(Symfony\Component\Security\Core\Authentication\Token\UsernamePasswordToken))
#4 /var/www/SIGE4/app/cache/dev/classes.php(2591): Escape\WSSEAuthenticationBundle\Security\Http\Firewall\Listener->handle(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent))
#5 [internal function]: Symfony\Component\Security\Http\Firewall->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\HttpKernel\Debug\TraceableEventDispatcher))
#6 /var/www/SIGE4/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/Debug/WrappedListener.php(61): call_user_func(Array, Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\HttpKernel\Debug\TraceableEventDispatcher))
#7 [internal function]: Symfony\Component\EventDispatcher\Debug\WrappedListener->__invoke(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\ContainerAwareEventDispatcher))
#8 /var/www/SIGE4/app/cache/dev/classes.php(1858): call_user_func(Object(Symfony\Component\EventDispatcher\Debug\WrappedListener), Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\ContainerAwareEventDispatcher))
#9 /var/www/SIGE4/app/cache/dev/classes.php(1773): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent))
#10 /var/www/SIGE4/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/Debug/TraceableEventDispatcher.php(140): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent))
#11 /var/www/SIGE4/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php(120): Symfony\Component\EventDispatcher\Debug\TraceableEventDispatcher->dispatch('kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent))
#12 /var/www/SIGE4/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php(62): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1)
#13 /var/www/SIGE4/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/DependencyInjection/ContainerAwareHttpKernel.php(69): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#14 /var/www/SIGE4/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(185): Symfony\Component\HttpKernel\DependencyInjection\ContainerAwareHttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#15 /var/www/SIGE4/web/app_dev.php(30): Symfony\Component\HttpKernel\Kernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#16 {main}
 
###############################################################
###############################################################
[2016-09-08 22:43:19]: Symfony\Component\Debug\Exception\ContextErrorException   codigo: 0
  mensaje: Notice: Undefined variable: token
  clase: /var/www/SIGE4/vendor/escapestudios/wsse-authentication-bundle/Escape/WSSEAuthenticationBundle/Security/Core/Authentication/Provider/Provider.php
  linea: 89
  metodo: handleError
  traza: #0 /var/www/SIGE4/vendor/escapestudios/wsse-authentication-bundle/Escape/WSSEAuthenticationBundle/Security/Core/Authentication/Provider/Provider.php(89): Symfony\Component\Debug\ErrorHandler->handleError(8, 'Undefined varia...', '/var/www/SIGE4/...', 89, Array)
#1 /var/www/SIGE4/vendor/escapestudios/wsse-authentication-bundle/Escape/WSSEAuthenticationBundle/Security/Core/Authentication/Provider/Provider.php(77): Escape\WSSEAuthenticationBundle\Security\Core\Authentication\Provider\Provider->sendResponse(Object(SIGE\SecurityManagerBundle\Entity\Usuario))
#2 /var/www/SIGE4/app/cache/dev/classes.php(2676): Escape\WSSEAuthenticationBundle\Security\Core\Authentication\Provider\Provider->authenticate(Object(Symfony\Component\Security\Core\Authentication\Token\UsernamePasswordToken))
#3 /var/www/SIGE4/vendor/escapestudios/wsse-authentication-bundle/Escape/WSSEAuthenticationBundle/Security/Http/Firewall/Listener.php(93): Symfony\Component\Security\Core\Authentication\AuthenticationProviderManager->authenticate(Object(Symfony\Component\Security\Core\Authentication\Token\UsernamePasswordToken))
#4 /var/www/SIGE4/app/cache/dev/classes.php(2591): Escape\WSSEAuthenticationBundle\Security\Http\Firewall\Listener->handle(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent))
#5 [internal function]: Symfony\Component\Security\Http\Firewall->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\HttpKernel\Debug\TraceableEventDispatcher))
#6 /var/www/SIGE4/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/Debug/WrappedListener.php(61): call_user_func(Array, Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\HttpKernel\Debug\TraceableEventDispatcher))
#7 [internal function]: Symfony\Component\EventDispatcher\Debug\WrappedListener->__invoke(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\ContainerAwareEventDispatcher))
#8 /var/www/SIGE4/app/cache/dev/classes.php(1858): call_user_func(Object(Symfony\Component\EventDispatcher\Debug\WrappedListener), Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\ContainerAwareEventDispatcher))
#9 /var/www/SIGE4/app/cache/dev/classes.php(1773): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent))
#10 /var/www/SIGE4/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/Debug/TraceableEventDispatcher.php(140): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent))
#11 /var/www/SIGE4/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php(120): Symfony\Component\EventDispatcher\Debug\TraceableEventDispatcher->dispatch('kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent))
#12 /var/www/SIGE4/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php(62): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1)
#13 /var/www/SIGE4/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/DependencyInjection/ContainerAwareHttpKernel.php(69): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#14 /var/www/SIGE4/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(185): Symfony\Component\HttpKernel\DependencyInjection\ContainerAwareHttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#15 /var/www/SIGE4/web/app_dev.php(30): Symfony\Component\HttpKernel\Kernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#16 {main}
 
###############################################################
###############################################################
[2016-09-08 22:43:59]: Symfony\Component\Debug\Exception\ContextErrorException   codigo: 0
  mensaje: Notice: Undefined variable: token
  clase: /var/www/SIGE4/vendor/escapestudios/wsse-authentication-bundle/Escape/WSSEAuthenticationBundle/Security/Core/Authentication/Provider/Provider.php
  linea: 89
  metodo: handleError
  traza: #0 /var/www/SIGE4/vendor/escapestudios/wsse-authentication-bundle/Escape/WSSEAuthenticationBundle/Security/Core/Authentication/Provider/Provider.php(89): Symfony\Component\Debug\ErrorHandler->handleError(8, 'Undefined varia...', '/var/www/SIGE4/...', 89, Array)
#1 /var/www/SIGE4/vendor/escapestudios/wsse-authentication-bundle/Escape/WSSEAuthenticationBundle/Security/Core/Authentication/Provider/Provider.php(77): Escape\WSSEAuthenticationBundle\Security\Core\Authentication\Provider\Provider->sendResponse(Object(SIGE\SecurityManagerBundle\Entity\Usuario), Object(Symfony\Component\Security\Core\Authentication\Token\UsernamePasswordToken))
#2 /var/www/SIGE4/app/cache/dev/classes.php(2676): Escape\WSSEAuthenticationBundle\Security\Core\Authentication\Provider\Provider->authenticate(Object(Symfony\Component\Security\Core\Authentication\Token\UsernamePasswordToken))
#3 /var/www/SIGE4/vendor/escapestudios/wsse-authentication-bundle/Escape/WSSEAuthenticationBundle/Security/Http/Firewall/Listener.php(93): Symfony\Component\Security\Core\Authentication\AuthenticationProviderManager->authenticate(Object(Symfony\Component\Security\Core\Authentication\Token\UsernamePasswordToken))
#4 /var/www/SIGE4/app/cache/dev/classes.php(2591): Escape\WSSEAuthenticationBundle\Security\Http\Firewall\Listener->handle(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent))
#5 [internal function]: Symfony\Component\Security\Http\Firewall->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\HttpKernel\Debug\TraceableEventDispatcher))
#6 /var/www/SIGE4/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/Debug/WrappedListener.php(61): call_user_func(Array, Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\HttpKernel\Debug\TraceableEventDispatcher))
#7 [internal function]: Symfony\Component\EventDispatcher\Debug\WrappedListener->__invoke(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\ContainerAwareEventDispatcher))
#8 /var/www/SIGE4/app/cache/dev/classes.php(1858): call_user_func(Object(Symfony\Component\EventDispatcher\Debug\WrappedListener), Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\ContainerAwareEventDispatcher))
#9 /var/www/SIGE4/app/cache/dev/classes.php(1773): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent))
#10 /var/www/SIGE4/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/Debug/TraceableEventDispatcher.php(140): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent))
#11 /var/www/SIGE4/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php(120): Symfony\Component\EventDispatcher\Debug\TraceableEventDispatcher->dispatch('kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent))
#12 /var/www/SIGE4/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php(62): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1)
#13 /var/www/SIGE4/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/DependencyInjection/ContainerAwareHttpKernel.php(69): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#14 /var/www/SIGE4/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(185): Symfony\Component\HttpKernel\DependencyInjection\ContainerAwareHttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#15 /var/www/SIGE4/web/app_dev.php(30): Symfony\Component\HttpKernel\Kernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#16 {main}
 
